networks:
  default:
    external:
      name: proxy

services:
  app:
    image: ghcr.io/benderfactory/vault:main
    restart: unless-stopped
    expose:
      - '80'
    env_file:
      - .env
    environment:
      PORT: 80
      VIRTUAL_HOST: vault.benderfactory.com
      LETSENCRYPT_HOST: vault.benderfactory.com
