networks:
  default:
    external:
      name: proxy

services:
  app:
    image: ghcr.io/benderfactory/vault:mainwolbodo/members:latest
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: vault.benderfactory.com
      LETSENCRYPT_HOST: vault.benderfactory.com
