networks:
  default:
    external:
      name: proxy

services:
  app:
    image: ghcr.io/benderfactory/vault:mainwolbodo/members:latest
    restart: unless-stopped
    expose:
      - "80"
    environment:
      VITE_GRAPHQL_ENDPOINT: https://graphql.wolbodo.nl/v1/graphql
      PORT: 80
      VIRTUAL_HOST: members.wolbodo.nl
      CERT_NAME: wildcard
      AUTH_JWT_SECRET: $AUTH_JWT_SECRET
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_PORT: $EMAIL_PORT
      EMAIL_USER: $EMAIL_USER
      EMAIL_PASS: $EMAIL_PASS